{
 "title": "Resque",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Workers by Queue",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (queue) (resque_workers_per_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Working Workers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resque_working_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resque Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resque_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Per Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (queue) (resque_jobs_in_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(resque_job_executions_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Processing Ratio",
   "type": "timeseries",
   "description": "Ratio of queued jobs to workers processing those queues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max by (queue) (resque_processing_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate (resque_jobs_in_failed_queue[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}